[pytest]
# Amplia la informacion sovre fallos en los casos test
addopts = -ra
markers =
    population: Tests referentes a la generacion y/o reproduccion de la poblacion tanto inicial como generacional.
    fitness: Tests referentes al calculo de aptitud de individuos.
    parentselection: Tests referentes a la seleccion de padres para la reproduccion.
